[package]
name = "openjlc"
version = "2.0.1"
edition = "2024"

[dependencies]
chrono = "0.4"
zip = "2.5"
lazy_static = "1.4"
rand = "0.9"

[lib]
name = "openjlc"
path = "src/lib.rs"

[[bin]]
name = "openjlc"
path = "src/main.rs"